//auth
export const REDIRECTED = 'REDIRECTED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';


//Load project
export const FETCH_PROJECTS_START = 'FETCH_PROJECTS_START';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_ERROR = 'FETCH_PROJECTS_ERROR';

//load resource
export const FETCH_RESOURCES_START = 'FETCH_RESOURCES_START';
export const FETCH_RESOURCES_SUCCESS = 'FETCH_RESOURCES_SUCCESS';
export const FETCH_RESOURCES_ERROR = 'FETCH_RESOURCES_ERROR';

//LOAD COLUMN
export const FETCH_COLUMN_START = 'FETCH_COLUMN_START';
export const FETCH_COLUMN_SUCCESS = 'FETCH_COLUMN_SUCCESS';
export const FETCH_COLUMN_ERROR = 'FETCH_COLUMN_ERROR';

//MANIPULATE resource
export const ADD_RESOURCE = 'ADD_RESOURCE';
export const REMOVE_RESOURCE = 'REMOVE_RESOURCE';
export const EDIT_RESOURCE = 'EDIT_RESOURCE';

//MANIPULATE COLUMN
export const ADD_COLUMN = 'ADD_COLUMN';
export const REMOVE_COLUMN = 'REMOVE_COLUMN';
export const EDIT_COLUMN = 'EDIT_COLUMN';

//Search
export const SEARCH_START = 'SEARCH_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_ERROR = 'SEARCH_ERROR';
